---
  # File mimics install isntructions here:
  #https://about.gitlab.com/install/#centos-7
  - name: Install required packages
    yum:
      name:
        - curl
        - policycoreutils-python
        - openssh-server
      state: latest
  
  - name: Enable and start sshd
    service:
      name: sshd
      state: started
      enabled: yes
  
  - name: Enable HTTP+HTTPS access
    firewalld:
      # This is how we use a variable
      service: "{{ item }}"
      permanent: yes
      state: enabled
     # The module will be run for each item
    with_items:
      - http
      - https
  
  - name: Reload firewalld
    service:
      name: firewalld
      state: reloaded
  
  - name: Install postfix
    yum:
      name:
        - postfix
      state: installed
  
  - name: Enable and start postfix
    service:
      name: postfix
      state: started
      enabled: true
  
  - name: Download GitLab package repository script
    get_url:
      url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh
      dest: /tmp/script.rpm.sh
  
  - name: Execute GitLab package repository script
    script: /tmp/script.rpm.sh
  
  - name: Install GitLab
    yum:
      update_cache: yes
      name: gitlab-ee
      state: latest
    environment:
      EXTERNAL_URL: http://gitlab.local